version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - '${WEB_PORT:-8000}:8000'
    networks:
      - internal-network
    volumes:
      - .:/home/appuser/app

  database:
    container_name: postgres
    image: postgres:17.5
    env_file:
      - .env
    expose:
      - 5432
    networks:
      - internal-network
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:

networks:
  internal-network:
